version: '3'
services:

  db:
    container_name: db
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: crud
    ports:
      - "3306:3306"

  app:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: app
    ports:
      - "80:80"
    volumes:
      - ./app:/code
    entrypoint:
      - /bin/sh
      - /code/conf/entrypoint.sh
    depends_on:
      - db
